import type { Metadata } from 'next'
import React from 'react'
import { Montserrat } from 'next/font/google'
import './globals.css'
import Provider from '@/app/components/providers/provider'
import BaseLayout from '@/app/components/layout/layout'

const inter = Montserrat({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Web developer',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
  params: { locale },
}: Readonly<{
  children: React.ReactNode
  params: { locale: string }
}>) {
  return (
    <html lang={locale}>
      <body className={inter.className}>
        <Provider>
          <BaseLayout>{children}</BaseLayout>
        </Provider>
      </body>
    </html>
  )
}
